Fix some Pylint Warnings
ateliedocodigo/py-healthcheck pull request #37
Opened 2022-04-23 13:32 UTC by hf-kklein

This PR fixes some pylint warnings.
It does not change the behaviour in any way.
See the single commit messages for details.

2022-05-11 20:07 UTC, luiscoms commented
Thanks for contributing @hf-kklein 
I will check why the tests are not running

2022-05-11 21:02 UTC, hf-kklein commented on healthcheck/environmentdump.py
> -class EnvironmentDump(object):
maybe this breaks python2

2022-06-11 03:35 UTC, luiscoms commented
Now you can rebase your branch in order to ensure tests are passing

2022-06-12 15:45 UTC, hf-kklein commented on healthcheck/healthcheck.py
> +        message = "NOT OK"
```suggestion
        message = 'NOT OK'
```

2022-06-12 15:46 UTC, hf-kklein commented on healthcheck/security.py
> +            result[key] = "********"
```suggestion
            result[key] = '********'
```

2022-06-12 15:50 UTC, hf-kklein commented on healthcheck/tornado_handler.py
> +        for k, v in headers.items:
```suggestion
        for k, v in headers.items():
```

2022-06-12 15:56 UTC, hf-kklein commented
> Now you can rebase your branch in order to ensure tests are passing

@luiscoms done :) it was one actual error and one violation of a quoting convention. it's all green now ✔

2022-06-14 14:58 UTC, luiscoms requested changes

2022-06-14 14:58 UTC, luiscoms commented on healthcheck/healthcheck.py
> +            logger.exception(exc)
This log could be error, not exception

2022-06-14 14:58 UTC, luiscoms commented on healthcheck/healthcheck.py
> +    data.update(kw)
I am not sure that this function is covered by tests, so this update should be tested

2022-06-15 12:47 UTC, hf-kklein commented on healthcheck/healthcheck.py
> +            logger.exception(exc)
432e8f347b45e34fc732a9a6f00092a90e4a43e0

2022-06-15 12:58 UTC, hf-kklein commented on healthcheck/healthcheck.py
> +    data.update(kw)
9b811386193c9a147b6420102bf5040f0b877e88

2022-06-21 02:19 UTC, luiscoms approved these changes

2022-06-21 02:19 UTC, merged